sonar.projectKey=simple-express-app
sonar.projectName=Simple Express App
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test

sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
